### ISSUE TITLE
tests fail with AssertionError: expected 'name 75' to equal 'Smith Family Recipe'

### ISSUE THREAD

**Issue by scross01** [zapier/zapier-platform-example-app-middleware#2]
```
  0 passing (387ms)
  1 failing

  1) triggers new recipe trigger should load recipes:

      AssertionError: expected 'name 75' to equal 'Smith Family Recipe'
      + expected - actual

      -name 75
      +Smith Family Recipe
      
      at Assertion.fail (node_modules/should/cjs/should.js:326:17)
      at Assertion.Object.defineProperty.value (node_modules/should/cjs/should.js:398:19)
      at test/triggers.js:15:35
  From previous event:
      at Context.<anonymous> (test/triggers.js:13:10)

```

**Comment by scross01** [comment]
retested with zapier-platform-cli 1.0.10 - working okay now.
